### ISSUE TITLE
Save user login & quest start events in postgresql

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-api#15]
Start saving user logins and already played quests so users can track what they've already played and indicate it in the app.

**Comment by toddmedema** [comment]
Sounds like two new tables, players and plays - which means we'll want to do this after we have the handle new Sequelize update :) As a bonus, will give us better analytics around quest plays, user behavior and quest duration

- should we differentiate between app users ("players") and QC users ("authors")? Probably?

Players:
- Google ID (aka user id)
- email (if we can't derive it from the Google ID)
- lastLogin
- loginCount? Could be handy from a marketing / re-engagement standpoint

Plays:
- user id
- quest id
- start time
- end time

API updates:
- on user login, increment / update lastLogin / loginCount, and additionally return an object listing quest id: (most recent) end time
- new /analytics/quest/start endpoint (or /analytics/play/start? or a more generic /analytics endpoint... something for the app to hit to record to the plays table
  - don't need the start and end time from the user app... always record it in server UTC time when message received
  - since it'll be coming in as two separate messages, we'll have to run an UPDATE query, adding the end time to the row that matches the quest and user id and has the most recent (max?) start time and no end time

App / UI updates:
- when we fire quest_start and quest_end analytics events, also hit the new /analytics API endpoint
- when displaying quest elements, if it's in their previously played dictionary, dim it and show a "last played XXXX" at the bottom
- perhaps we should make a unified "QuestListButton" element that'll be used on both the homepage and search page, now that the logic here continues to get more complex

**Comment by toddmedema** [comment]
Closed by https://github.com/ExpeditionRPG/expedition-api/pull/61
